name: yyc_scan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  persistent_bottom_nav_bar: ^5.0.2
  mobile_scanner: ^4.0.0
  google_maps_flutter: ^2.5.3
  slide_indexed_stack: ^0.0.1
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
